import { create } from "zustand";

const useStyleStore = create((set) => ({
  // ---------------------------------------------Button--------------------------------
  // Primary
  btnPrimaryBackground: "",
  btnPrimaryTextColor: "",
  btnPrimaryBorderRadius: "",
  btnPrimaryOutline: "",
  btnPrimaryOutlineText: "",
  btnPrimaryHoverBackground: "",
  btnPrimaryHoverText: "",
  btnPrimaryActiveBackground: "",
  btnPrimaryActiveText: "",
  // Secondary
  btnSecondaryBackground: "",
  btnSecondaryTextColor: "",
  btnSecondaryBorderRadius: "",
  btnSecondaryOutline: "",
  btnSecondaryOutlineText: "",
  btnSecondaryHoverBackground: "",
  btnSecondaryHoverText: "",
  btnSecondaryActiveBackground: "",
  btnSecondaryActiveText: "",
  // Success
  btnSuccessBackground: "",
  btnSuccessTextColor: "",
  btnSuccessBorderRadius: "",
  btnSuccessOutline: "",
  btnSuccessOutlineText: "",
  btnSuccessHoverBackground: "",
  btnSuccessHoverText: "",
  btnSuccessActiveBackground: "",
  btnSuccessActiveText: "",
  // Error
  btnErrorBackground: "",
  btnErrorTextColor: "",
  btnErrorBorderRadius: "",
  btnErrorOutline: "",
  btnErrorOutlineText: "",
  btnErrorHoverBackground: "",
  btnErrorHoverText: "",
  btnErrorActiveBackground: "",
  btnErrorActiveText: "",
  // Warning
  btnWarningBackground: "",
  btnWarningTextColor: "",
  btnWarningBorderRadius: "",
  btnWarningOutline: "",
  btnWarningOutlineText: "",
  btnWarningHoverBackground: "",
  btnWarningHoverText: "",
  btnWarningActiveBackground: "",
  btnWarningActiveText: "",
  // Info
  btnInfoBackground: "",
  btnInfoTextColor: "",
  btnInfoBorderRadius: "",
  btnInfoOutline: "",
  btnInfoOutlineText: "",
  btnInfoHoverBackground: "",
  btnInfoHoverText: "",
  btnInfoActiveBackground: "",
  btnInfoActiveText: "",

  // ---------------------------------------------Button--------------------------------
  popUpCardBackground: "",
  popUpSuccessBackground: "",
  popUpSuccessColor: "",
  popUpFailedBackground: "",
  popUpFailedColor: "",
  popUpTextColor: "",
  popUpBtnBackground: "",
  popUpBtnTextColor: "",

  // ---------------------------- Login -------------------------------
  cardLoginBackground: "",
  cardLoginTextColor: "",
  cardLoginHeading: "",
  loginLabelColor: "",
  loginInputBackground: "",
  loginInputTextColor: "",
  loginButtonBackground: "",
  loginButtonTextColor: "",
  // ---------------------------- Login -------------------------------

  // Header
  headerBackgroundColor: "",
  headerBackgroundImage: "",
  headerBackgroundGradient: "",
  headerBorderWidth: "",
  headerBorderStyle: "",
  headerBorderColor: "",
  headerShadow: "",
  headerColor: "",
  headerFilterBlur: "",
  headerFontFamily: "",
  headerFontSize: "",
  headerBorderRadius: "",
  headerHeight: "",
  // End Header

  // Sidebar
  sidebarBackgroundColor: "",
  sidebarBackgroundImage: "",
  sidebarBackgroundGradient: "",
  sidebarBorderWidth: "",
  sidebarBorderStyle: "",
  sidebarBorderColor: "",
  sidebarShadowThick: "",
  sidebarShadowGradient: "",
  sidebarColor: "",
  sidebarFilterBlur: "",
  sidebarFontFamily: "",
  sidebarFontSize: "",
  sidebarBorderRadius: "",
  sidebarWidth: "225px",

  // Nav Link
  sidebarNavLinkBackgroundColor: "",
  sidebarNavLinkColor: "",
  sidebarNavLinkIconColor: "",
  sidebarNavHeadingColor: "",
  // Nav Link Active
  sidebarNavLinkActiveBackgroundColor: "",
  sidebarNavLinkActiveColor: "",

  // End Sidebar

  // Content
  contentBackgroundColor: "",
  contentBackgroundImage: "",
  contentBackgroundGradient: "",
  contentBorderWidth: "",
  contentBorderStyle: "",
  contentBorderColor: "",
  contentShadowThick: "",
  contentShadowGradient: "",
  contentColor: "",
  contentFilterBlur: "",
  contentFontFamily: "",
  contentFontSize: "",
  contentBorderRadius: "",
  // End Content
  // Selected
  footerBackgroundColor: "",
  footerBackgroundImage: "",
  footerBackgroundGradient: "",
  footerBorderWidth: "",
  footerBorderStyle: "",
  footerBorderColor: "",
  footerShadow: "",
  footerColor: "",
  footerFilterBlur: "",
  footerFontFamily: "",
  footerFontSize: "",
  footerBorderRadius: "",
  footerHeight: "",
  // End Selected
  // --------------------------------------------------- Modal ------------------------------------------
  // Modal Card
  modalCardBackgroundColor: "",
  modalCardBackgroundImage: "",
  modalCardBackgroundGradient: "",
  modalCardBorderWidth: "",
  modalCardBorderStyle: "",
  modalCardBorderColor: "",
  modalCardShadow: "",
  modalCardColor: "",
  modalCardFilterBlur: "",
  modalCardFontFamily: "",
  modalCardFontSize: "",
  modalCardBorderRadius: "",
  modalCardHeight: "",
  // Modal Header
  modalHeaderBackgroundColor: "",
  modalHeaderBackgroundImage: "",
  modalHeaderBackgroundGradient: "",
  modalHeaderBorderWidth: "",
  modalHeaderBorderStyle: "",
  modalHeaderBorderColor: "",
  modalHeaderShadow: "",
  modalHeaderColor: "",
  modalHeaderFilterBlur: "",
  modalHeaderFontFamily: "",
  modalHeaderFontSize: "",
  modalHeaderBorderRadius: "",
  modalHeaderHeight: "",
  // End Modal Header
  // Modal Body
  modalBodyBackgroundColor: "",
  modalBodyBackgroundImage: "",
  modalBodyBackgroundGradient: "",
  modalBodyBorderWidth: "",
  modalBodyBorderStyle: "",
  modalBodyBorderColor: "",
  modalBodyShadow: "",
  modalBodyColor: "",
  modalBodyFilterBlur: "",
  modalBodyFontFamily: "",
  modalBodyFontSize: "",
  modalBodyBorderRadius: "",
  modalBodyHeight: "",
  // End Modal Body
  // Modal Footer
  modalFooterBackgroundColor: "",
  modalFooterBackgroundImage: "",
  modalFooterBackgroundGradient: "",
  modalFooterBorderWidth: "",
  modalFooterBorderStyle: "",
  modalFooterBorderColor: "",
  modalFooterShadow: "",
  modalFooterColor: "",
  modalFooterFilterBlur: "",
  modalFooterFontFamily: "",
  modalFooterFontSize: "",
  modalFooterBorderRadius: "",
  modalFooterHeight: "",
  // End Modal Footer

  // End Modal

  // ----------------------------------------- Card ------------------------------------------
  // Card
  cardBackgroundColor: "",
  cardBackgroundImage: "",
  cardBackgroundGradient: "",
  cardBorderWidth: "",
  cardBorderStyle: "",
  cardBorderColor: "",
  cardShadow: "",
  cardColor: "",
  cardFilterBlur: "",
  cardFontFamily: "",
  cardFontSize: "",
  cardBorderRadius: "",
  cardHeight: "",
  // Card Header
  cardHeaderBackgroundColor: "",
  cardHeaderBackgroundImage: "",
  cardHeaderBackgroundGradient: "",
  cardHeaderBorderWidth: "",
  cardHeaderBorderStyle: "",
  cardHeaderBorderColor: "",
  cardHeaderShadow: "",
  cardHeaderColor: "",
  cardHeaderFilterBlur: "",
  cardHeaderFontFamily: "",
  cardHeaderFontSize: "",
  cardHeaderBorderRadius: "",
  cardHeaderHeight: "",
  // Card Content
  cardContentBackgroundColor: "",
  cardContentBackgroundImage: "",
  cardContentBackgroundGradient: "",
  cardContentBorderWidth: "",
  cardContentBorderStyle: "",
  cardContentBorderColor: "",
  cardContentShadow: "",
  cardContentColor: "",
  cardContentFilterBlur: "",
  cardContentFontFamily: "",
  cardContentFontSize: "",
  cardContentBorderRadius: "",
  cardContentHeight: "",
  // Card Footer
  cardFooterBackgroundColor: "",
  cardFooterBackgroundImage: "",
  cardFooterBackgroundGradient: "",
  cardFooterBorderWidth: "",
  cardFooterBorderStyle: "",
  cardFooterBorderColor: "",
  cardFooterShadow: "",
  cardFooterColor: "",
  cardFooterFilterBlur: "",
  cardFooterFontFamily: "",
  cardFooterFontSize: "",
  cardFooterBorderRadius: "",
  cardFooterHeight: "",
  cardBorderRadius: "",
  // ----------------------------------------- End Card ------------------------------------------

  // ----------------------------------------- Table ------------------------------------------
  // Table
  tableBackgroundColor: "",
  tableBackgroundImage: "",
  tableBackgroundGradient: "",
  tableBorderWidth: "",
  tableBorderStyle: "",
  tableBorderColor: "",
  tableShadow: "",
  tableColor: "",
  tableFilterBlur: "",
  tableFontFamily: "",
  tableFontSize: "",
  tableBorderRadius: "",
  tableHeight: "",
  // Table Header
  tableHeadBackgroundColor: "",
  tableHeadBackgroundImage: "",
  tableHeadBackgroundGradient: "",
  tableHeadBorderWidth: "",
  tableHeadBorderStyle: "",
  tableHeadBorderColor: "",
  tableHeadShadow: "",
  tableHeadColor: "",
  tableHeadFilterBlur: "",
  tableHeadFontFamily: "",
  tableHeadFontSize: "",
  tableHeadBorderRadius: "",
  tableHeadHeight: "",
  tableHeadPadding: "",
  // Table Body
  tableBodyBackgroundColor: "",
  tableRowOddBackgroundColor: "",
  tableRowEvenBackgroundColor: "",
  tableBodyBackgroundImage: "",
  tableBodyBackgroundGradient: "",
  tableBodyBorderWidth: "",
  tableBodyBorderStyle: "",
  tableBodyBorderColor: "",
  tableBodyShadow: "",
  tableBodyColor: "",
  tableBodyFilterBlur: "",
  tableBodyFontFamily: "",
  tableBodyFontSize: "",
  tableBodyBorderRadius: "",
  tableBodyHeight: "",
  tableBodyHeight: "",
  // Table Foot
  tableFootBackgroundColor: "",
  tableFootBackgroundImage: "",
  tableFootBackgroundGradient: "",
  tableFootBorderWidth: "",
  tableFootBorderStyle: "",
  tableFootBorderColor: "",
  tableFootShadow: "",
  tableFootColor: "",
  tableFootFilterBlur: "",
  tableFootFontFamily: "",
  tableFootFontSize: "",
  tableFootBorderRadius: "",
  tableFootHeight: "",
  tableBorderRadius: "",
  tableFootPadding: "",

  // ------------------------------- Additional Table ------------------------------------------
  // Table Select
  tableSelectBackgroundColor: "",
  tableSelectBackgroundImage: "",
  tableSelectBackgroundGradient: "",
  tableSelectBorderWidth: "",
  tableSelectBorderStyle: "",
  tableSelectBorderColor: "",
  tableSelectShadow: "",
  tableSelectColor: "",
  tableSelectFilterBlur: "",
  tableSelectFontFamily: "",
  tableSelectFontSize: "",
  tableSelectBorderRadius: "",
  tableSelectHeight: "",
  tableSelectBorderRadius: "",
  tableSelectPadding: "",
  // Table Input
  tableInputBackgroundColor: "",
  tableInputBackgroundImage: "",
  tableInputBackgroundGradient: "",
  tableInputBorderWidth: "",
  tableInputBorderStyle: "",
  tableInputBorderColor: "",
  tableInputShadow: "",
  tableInputColor: "",
  tableInputFilterBlur: "",
  tableInputFontFamily: "",
  tableInputFontSize: "",
  tableInputBorderRadius: "",
  tableInputHeight: "",
  tableInputBorderRadius: "",
  tableInputPadding: "",
  // Table Show
  tableShowBackgroundColor: "",
  tableShowBackgroundImage: "",
  tableShowBackgroundGradient: "",
  tableShowBorderWidth: "",
  tableShowBorderStyle: "",
  tableShowBorderColor: "",
  tableShowShadow: "",
  tableShowColor: "",
  tableShowFilterBlur: "",
  tableShowFontFamily: "",
  tableShowFontSize: "",
  tableShowBorderRadius: "",
  tableShowHeight: "",
  tableShowBorderRadius: "",
  tableShowPadding: "",
  // Table Pagination
  tablePaginationBackgroundColor: "",
  tablePaginationActiveBackgroundColor: "",
  tablePaginationActiveColor: "",
  tablePaginationBackgroundImage: "",
  tablePaginationBackgroundGradient: "",
  tablePaginationBorderWidth: "",
  tablePaginationBorderStyle: "",
  tablePaginationBorderColor: "",
  tablePaginationShadow: "",
  tablePaginationColor: "",
  tablePaginationFilterBlur: "",
  tablePaginationFontFamily: "",
  tablePaginationFontSize: "",
  tablePaginationBorderRadius: "",
  tablePaginationHeight: "",
  tablePaginationBorderRadius: "",
  tablePaginationPadding: "",

  // ----------------------------------------- Child Table ------------------------------------------
  tableChildBackgroundColor: "",
  tableChildBackgroundImage: "",
  tableChildBackgroundGradient: "",
  tableChildBorderWidth: "",
  tableChildBorderStyle: "",
  tableChildBorderColor: "",
  tableChildShadow: "",
  tableChildColor: "",
  tableChildFilterBlur: "",
  tableChildFontFamily: "",
  tableChildFontSize: "",
  tableChildBorderRadius: "",
  tableChildHeight: "",
  tableChildBorderRadius: "",
  tableChildPadding: "",

  // ----------------------------------------- End Child Table ------------------------------------------

  // ----------------------------------------- End Card ------------------------------------------
  // ----------------------------------------- Breadcrumbs ---------------------------------------
  // Breadcrumbs
  breadcrumbsBackgroundColor: "",
  breadcrumbsBackgroundImage: "",
  breadcrumbsBackgroundGradient: "",
  breadcrumbsBorderWidth: "",
  breadcrumbsBorderStyle: "",
  breadcrumbsBorderColor: "",
  breadcrumbsShadow: "",
  breadcrumbsColor: "",
  breadcrumbsFilterBlur: "",
  breadcrumbsFontFamily: "",
  breadcrumbsFontSize: "",
  breadcrumbsBorderRadius: "",
  breadcrumbsHeight: "",

  // Breadcrumbs item
  breadcrumbsItemColor: "",
  breadcrumbsItemDividerColor: "",
  breadcrumbsItemPaddingLeft: "",
  // Breadcrumbs item active
  breadcrumbsItemActiveColor: "",

  // ----------------------------------------- End Breadcrumbs -----------------------------------
  // ----------------------------------------- Form ----------------------------------------------
  // Label
  formLabelColor: "",
  formLabelFontSize: "",
  formLabelFontFamily: "",
  formLabelFontWeight: "",
  // End Label
  // Input
  formInputBackgroundColor: "",
  formInputBackgroundImage: "",
  formInputBackgroundGradient: "",
  formInputBorderWidth: "",
  formInputBorderStyle: "",
  formInputBorderColor: "",
  formInputShadow: "",
  formInputColor: "",
  formInputFilterBlur: "",
  formInputFontFamily: "",
  formInputFontSize: "",
  formInputBorderRadius: "",
  formInputPadding: "",
  formInputHeight: "",
  // End Input
  // ----------------------------------------- End Form ------------------------------------------
  // Color Theme
  // COLOR PRIMARY
  colorPrimary: "#007bff",
  colorPrimary900: "#007bffe6",
  colorPrimary800: "#007bffcc",
  colorPrimary700: "#007bffb3",
  colorPrimary600: "#007bff99",
  colorPrimary500: "#007bff80",
  colorPrimary400: "#007bff66",
  colorPrimary300: "#007bff4d",
  colorPrimary200: "#007bff33",
  colorPrimary100: "#007bff1a",
  colorPrimary50: "#007bff0d",
  // COLOR SECONDARY
  colorSecondary: "#6c757d",
  colorSecondary900: "#6c757de6",
  colorSecondary800: "#6c757dcc",
  colorSecondary700: "#6c757db3",
  colorSecondary600: "#6c757d99",
  colorSecondary500: "#6c757d80",
  colorSecondary400: "#6c757d66",
  colorSecondary300: "#6c757d4d",
  colorSecondary200: "#6c757d33",
  colorSecondary100: "#6c757d1a",
  colorSecondary50: "#6c757d0d",
  // COLOR SUCCESS
  colorSuccess: "#28a745",
  colorSuccess900: "#28a745e6",
  colorSuccess800: "#28a745cc",
  colorSuccess700: "#28a745b3",
  colorSuccess600: "#28a74599",
  colorSuccess500: "#28a74580",
  colorSuccess400: "#28a74566",
  colorSuccess300: "#28a7454d",
  colorSuccess200: "#28a74533",
  colorSuccess100: "#28a7451a",
  colorSuccess50: "#28a7450d",
  // COLOR WARNING
  colorWarning: "#ffc107",
  colorWarning900: "#ffc107e6",
  colorWarning800: "#ffc107cc",
  colorWarning700: "#ffc107b3",
  colorWarning600: "#ffc10799",
  colorWarning500: "#ffc10780",
  colorWarning400: "#ffc10766",
  colorWarning300: "#ffc1074d",
  colorWarning200: "#ffc10733",
  colorWarning100: "#ffc1071a",
  colorWarning50: "#ffc1070d",
  // COLOR INFO
  colorInfo: "#17a2b8",
  colorInfo900: "#17a2b8e6",
  colorInfo800: "#17a2b8cc",
  colorInfo700: "#17a2b8b3",
  colorInfo600: "#17a2b899",
  colorInfo500: "#17a2b880",
  colorInfo400: "#17a2b866",
  colorInfo300: "#17a2b84d",
  colorInfo200: "#17a2b833",
  colorInfo100: "#17a2b81a",
  colorInfo50: "#17a2b80d",
  // COLOR DANGER
  colorDanger: "#dc3545",
  colorDanger900: "#dc3545e6",
  colorDanger800: "#dc3545cc",
  colorDanger700: "#dc3545b3",
  colorDanger600: "#dc354599",
  colorDanger500: "#dc354580",
  colorDanger400: "#dc354566",
  colorDanger300: "#dc35454d",
  colorDanger200: "#dc354533",
  colorDanger100: "#dc35451a",
  colorDanger50: "#dc35450d",
  // ----------------------------------------- Toast ------------------------------------------
  // COLOR Dark
  colorDark: "#343a40",
  colorDark900: "#343a40e6",
  colorDark800: "#343a40cc",
  colorDark700: "#343a40b3",
  colorDark600: "#343a4099",
  colorDark500: "#343a4080",
  colorDark400: "#343a4066",
  colorDark300: "#343a404d",
  colorDark200: "#343a4033",
  colorDark100: "#343a401a",
  colorDark50: "#343a400d",
  // COLOR Light
  colorLight: "#ffffff",
  colorLight900: "#ffffffe6",
  colorLight800: "#ffffffcc",
  colorLight700: "#ffffffb3",
  colorLight600: "#ffffff99",
  colorLight500: "#ffffff80",
  colorLight400: "#ffffff66",
  colorLight300: "#ffffff4d",
  colorLight200: "#ffffff33",
  colorLight100: "#ffffff1a",
  colorLight50: "#ffffff0d",
  // ----------------------------------------- Toast ------------------------------------------
  // toast Header
  toastBackgroundColor: "",
  toastBackgroundImage: "",
  toastBackgroundGradient: "",
  toastBorderWidth: "",
  toastBorderStyle: "",
  toastBorderColor: "",
  toastShadow: "",
  toastColor: "",
  toastFilterBlur: "",
  toastFontFamily: "",
  toastFontSize: "",
  toastBorderRadius: "",
  toastHeight: "",
  // toast Header
  toastHeaderBackgroundColor: "",
  toastHeaderBackgroundImage: "",
  toastHeaderBackgroundGradient: "",
  toastHeaderBorderWidth: "",
  toastHeaderBorderStyle: "",
  toastHeaderBorderColor: "",
  toastHeaderShadow: "",
  toastHeaderColor: "",
  toastHeaderFilterBlur: "",
  toastHeaderFontFamily: "",
  toastHeaderFontSize: "",
  toastHeaderBorderRadius: "",
  toastHeaderHeight: "",
  // toast Content
  toastContentBackgroundColor: "",
  toastContentBackgroundImage: "",
  toastContentBackgroundGradient: "",
  toastContentBorderWidth: "",
  toastContentBorderStyle: "",
  toastContentBorderColor: "",
  toastContentShadow: "",
  toastContentColor: "",
  toastContentFilterBlur: "",
  toastContentFontFamily: "",
  toastContentFontSize: "",
  toastContentBorderRadius: "",
  toastContentHeight: "",
  // ----------------------------------------- Toast ------------------------------------------
  // ----------------------------------------- Tabs ------------------------------------------
  // Tabs Active
  tabsActiveContentBackgroundColor: "",
  tabsActiveContentBackgroundImage: "",
  tabsActiveContentBackgroundGradient: "",
  tabsActiveContentBorderWidth: "",
  tabsActiveContentBorderStyle: "",
  tabsActiveContentBorderColor: "",
  tabsActiveContentShadow: "",
  tabsActiveContentColor: "",
  tabsActiveContentFilterBlur: "",
  tabsActiveContentFontFamily: "",
  tabsActiveContentFontSize: "",
  tabsActiveContentBorderRadius: "",
  tabsActiveContentHeight: "",
  // Tabs Item
  tabsItemContentBackgroundColor: "",
  tabsItemContentBackgroundImage: "",
  tabsItemContentBackgroundGradient: "",
  tabsItemContentBorderWidth: "",
  tabsItemContentBorderStyle: "",
  tabsItemContentBorderColor: "",
  tabsItemContentShadow: "",
  tabsItemContentColor: "",
  tabsItemContentFilterBlur: "",
  tabsItemContentFontFamily: "",
  tabsItemContentFontSize: "",
  tabsItemContentBorderRadius: "",
  tabsItemContentHeight: "",

  // ----------------------------------------- End Tabs ------------------------------------------
  // ----------------------------------------- Alert ------------------------------------------
  // Alert
  alertBackgroundColor: "",
  alertBackgroundImage: "",
  alertBackgroundGradient: "",
  alertBorderWidth: "",
  alertBorderStyle: "",
  alertBorderColor: "",
  alertShadow: "",
  alertColor: "",
  alertFilterBlur: "",
  alertFontFamily: "",
  alertFontSize: "",
  alertBorderRadius: "",
  alertHeight: "",

  // ----------------------------------------- End Alert ------------------------------------------

  // ----------------------------------------- Pop up ------------------------------------------
  // PopUp
  popUpSuccessBackgroundColor: "",
  popUpFailedBackgroundColor: "",

  popUpCardBackgroundColor: "",
  popUpBackgroundImage: "",
  popUpBackgroundGradient: "",
  popUpBorderWidth: "",
  popUpBorderStyle: "",
  popUpBorderColor: "",
  popUpShadow: "",
  popUpColor: "",
  popUpFilterBlur: "",
  popUpFontFamily: "",
  popUpFontSize: "",
  popUpBorderRadius: "",
  popUpHeight: "",
  // ----------------------------------------- End Pop up ------------------------------------------

  // ----------------------------------------- Sub Header ------------------------------------------
  // SUB HEADER
  subHeaderBackgroundColor: "",
  subHeaderBackgroundImage: "",
  subHeaderBackgroundGradient: "",
  subHeaderBorderWidth: "",
  subHeaderBorderStyle: "",
  subHeaderBorderColor: "",
  subHeaderShadow: "",
  subHeaderColor: "",
  subHeaderFilterBlur: "",
  subHeaderFontFamily: "",
  subHeaderFontSize: "",
  subHeaderBorderRadius: "",
  subHeaderHeight: "",

  // SUB HEADER TITLE
  subHeaderTitleBackgroundColor: "",
  subHeaderTitleBackgroundImage: "",
  subHeaderTitleBackgroundGradient: "",
  subHeaderTitleBorderWidth: "",
  subHeaderTitleBorderStyle: "",
  subHeaderTitleBorderColor: "",
  subHeaderTitleShadow: "",
  subHeaderTitleColor: "",
  subHeaderTitleFilterBlur: "",
  subHeaderTitleFontFamily: "",
  subHeaderTitleFontSize: "",
  subHeaderTitleFontWeight: "",
  subHeaderTitleBorderRadius: "",
  subHeaderTitleHeight: "",

  // SUB HEADER Text
  subHeaderTextBackgroundColor: "",
  subHeaderTextBackgroundImage: "",
  subHeaderTextBackgroundGradient: "",
  subHeaderTextBorderWidth: "",
  subHeaderTextBorderStyle: "",
  subHeaderTextBorderColor: "",
  subHeaderTextShadow: "",
  subHeaderTextColor: "",
  subHeaderTextFilterBlur: "",
  subHeaderTextFontFamily: "",
  subHeaderTextFontSize: "",
  subHeaderTextBorderRadius: "",
  subHeaderTextHeight: "",

  // ----------------------------------------- End Sub Header ------------------------------------------
  // ----------------------------------------- Button --------------------------------------------------
  btnFontWeight: "",
  btnColor: "",
  btnTextAlign: "",
  btnBorderWidth: "",
  btnBorderColor: "",
  btnPadding: "",
  btnLineHeight: "",
  btnBorderRadius: "",
  // ----------------------------------------- End Button ----------------------------------------------

  // End Selected
  changeStyle: (state) => {
    console.log(state);
    const property = state.property;
    set({ [property]: state.value });
  },

  changeOpacityColor: (state) => {
    console.log(state, "Ini state");
    const property = state.property;
    set({ [property]: state.value });
    set({ [`${property}900`]: `${state.value}e6` });
    set({ [`${property}800`]: `${state.value}cc` });
    set({ [`${property}700`]: `${state.value}b3` });
    set({ [`${property}600`]: `${state.value}99` });
    set({ [`${property}500`]: `${state.value}80` });
    set({ [`${property}400`]: `${state.value}66` });
    set({ [`${property}300`]: `${state.value}4d` });
    set({ [`${property}200`]: `${state.value}33` });
    set({ [`${property}100`]: `${state.value}1a` });
    set({ [`${property}50`]: `${state.value}0d` });
  },

  changeTemplateStyle: (state) => {
    console.log(state);
    for (let index = 0; index < state.data.length; index++) {
      console.log(state.data[index]);
      let property = state.data[index].property;
      set({ [property]: state.data[index].value });
    }
  },
}));

export default useStyleStore;
